---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: flatnetworkips.flatnetwork.pandaria.io
spec:
  group: flatnetwork.pandaria.io
  names:
    kind: FlatNetworkIP
    plural: flatnetworkips
    shortNames:
    - flatnetworkip
    - flip
    - flips
    singular: flatnetworkip
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              addrs:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              macs:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              podId:
                nullable: true
                type: string
              subnet:
                nullable: true
                type: string
            type: object
          status:
            properties:
              addr:
                nullable: true
                type: string
              allocatedTimeStamp:
                nullable: true
                type: string
              failureMessage:
                nullable: true
                type: string
              mac:
                nullable: true
                type: string
              phase:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: flatnetworksubnets.flatnetwork.pandaria.io
spec:
  group: flatnetwork.pandaria.io
  names:
    kind: FlatNetworkSubnet
    plural: flatnetworksubnets
    shortNames:
    - flatnetworksubnet
    - flsubnet
    - flsubnets
    singular: flatnetworksubnet
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              cidr:
                nullable: true
                type: string
              flatMode:
                nullable: true
                type: string
              gateway:
                nullable: true
                type: string
              ipvlanFlag:
                nullable: true
                type: string
              master:
                nullable: true
                type: string
              mode:
                nullable: true
                type: string
              ranges:
                items:
                  properties:
                    from:
                      nullable: true
                      type: string
                    to:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              routeSettings:
                properties:
                  addClusterCIDR:
                    type: boolean
                  addNodeCIDR:
                    type: boolean
                  addPodIPToHost:
                    type: boolean
                  addServiceCIDR:
                    type: boolean
                  flatNetworkDefaultGateway:
                    type: boolean
                type: object
              routes:
                items:
                  properties:
                    dev:
                      nullable: true
                      type: string
                    dst:
                      nullable: true
                      type: string
                    priority:
                      type: integer
                    src:
                      nullable: true
                      type: string
                    via:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              vlan:
                type: integer
            type: object
          status:
            properties:
              failureMessage:
                nullable: true
                type: string
              gateway:
                nullable: true
                type: string
              phase:
                nullable: true
                type: string
              reservedIP:
                additionalProperties:
                  items:
                    properties:
                      from:
                        nullable: true
                        type: string
                      to:
                        nullable: true
                        type: string
                    type: object
                  nullable: true
                  type: array
                nullable: true
                type: object
              usedIP:
                items:
                  properties:
                    from:
                      nullable: true
                      type: string
                    to:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              usedIPCount:
                type: integer
              usedMac:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
